[package]
name = "dungeon_maze_common"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.2", features=["jpeg"] }
bevy_mesh_obj = "0.1.2"
noise = "0.9.0"
rand = "0.8.5"
serde = "1.0.214"
serde_json = "1.0.132"
strum = "0.26.3"
strum_macros = "0.26.4"
thiserror = "2.0.0"
