[package]
name = "dungeon_maze_proc_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
dungeon_maze_common = { path = "../common" }
serde_json = "1.0.132"
strum = "0.26.3"

[lib]
proc-macro = true
